
title: Axat Chaudhary
url: 'http://axatchaudhary.github.io'
baseurl: '/axatchaudhary.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2 #teal
#style: styles-3 #green
#style: styles-4 #purple
#style: styles-5 #orange
#style: styles-6 #black


#Profile information
name: Axat Chaudhary
tagline: Research Entusiast with a knack of ICT with Design
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: axat.chaudhary96@gmail.com
phone: +91 9033-9349-39
website: axatchaudhary.github.io
linkedin: axat-chaudhary
github: Axatchaudhary

# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.

# Science is what we understand well enough to explain to a computer. Art is everything else we do. - Donald Knuth
# Everyday life is like programming, I guess. If you love something you can put beauty into it. Donald Knuth
